from typing import Protocol
from uuid import UUID

from armybot.domain.entities import Deployment, Project, User, UserCredential
from armybot.domain.enums import CredentialProvider, UserStatus


class UserRepository(Protocol):
    async def get_by_telegram_id(self, telegram_id: int) -> User | None: ...

    async def add(self, user: User) -> None: ...

    async def update(self, user: User) -> None: ...

    async def list_by_status(self, status: UserStatus) -> list[User]: ...


class CredentialRepository(Protocol):
    async def upsert(self, credential: UserCredential) -> None: ...

    async def get(self, user_id: UUID, provider: CredentialProvider) -> UserCredential | None: ...

    async def list_for_user(self, user_id: UUID) -> list[UserCredential]: ...


class ProjectRepository(Protocol):
    async def get_by_repo(self, user_id: UUID, repo_url: str, branch: str) -> Project | None: ...

    async def add(self, project: Project) -> None: ...

    async def update(self, project: Project) -> None: ...

    async def list_for_user(self, user_id: UUID) -> list[Project]: ...


class DeploymentRepository(Protocol):
    async def add(self, deployment: Deployment) -> None: ...

    async def update(self, deployment: Deployment) -> None: ...

    async def latest_for_user(self, user_id: UUID, limit: int = 10) -> list[Deployment]: ...
